services:
  webapp:
    image: jaakdaemen/webapp:latest
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URL=mysql://root:rootpassword@database:3306/animals
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=animals
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  tests:
    build: .
    command: yarn test
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp
      - database 

volumes:
  mysql_data:
