---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Start application server
        run: yarn start &
        env:
          PORT: 3000

      - name: Wait for server to startsss
        run: sleep 10

      - name: Run tests
        run: yarn test

      - name: Stop application server
        run: |
          ps aux | grep node
          pkill -f "node.*server.js" || true
          killall node || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
